apiVersion: v1
kind: ConfigMap
metadata:
  name: nomad-config
  namespace: nomad
data:
  nomad.hcl: |
    log_level = "DEBUG"
    data_dir = "/opt/nomad/data"

    server {
      enabled          = true
      bootstrap_expect = 3
    }

    advertise {
      http = "{{ GetInterfaceIP \"eth0\" }}"
      rpc  = "{{ GetInterfaceIP \"eth0\" }}"
      serf = "{{ GetInterfaceIP \"eth0\" }}"
    }
