apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nomad-server
  namespace: nomad
spec:
  serviceName: "nomad"
  replicas: 3
  selector:
    matchLabels:
      app: nomad
  template:
    metadata:
      labels:
        app: nomad
    spec:
      containers:
      - name: nomad
        image: hashicorp/nomad
        ports:
        - containerPort: 4646
          name: http
        - containerPort: 4647
          name: rpc
        - containerPort: 4648
          name: serf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nomad
        - name: data
          mountPath: /opt/nomad/data
        - name: nomad-data
          mountPath: /var/lib/nomad
      volumes:
      - name: config-volume
        configMap:
          name: nomad-config
      - name: data
        emptyDir: {}
      - name: nomad-data
        emptyDir: {}
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: nomad
  namespace: nomad
spec:
  ports:
  - port: 4646
    name: http
  - port: 4647
    name: rpc
  - port: 4648
    name: serf
  clusterIP: None
  selector:
    app: nomad